name: pet_medical
description: Pet Medical App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_form_builder:
  cloud_firestore: ^2.2.2
  firebase_core :

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_driver:
    sdk: flutter
  integration_test:


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  Pets
      fonts:
        - asset: assets/fonts/Pets.ttf
